version: '3'

services:
  node_app:
    build: ./node
    container_name: node_app
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      DEVOPS: exadel
  
  java_app:
    image: jenkins
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    privileged: true
    user: root
    depends_on: [database]
    restart: unless-stopped
    environment: 
      JAVA_OPTS: "-Dhudson.footerURL=http://github.com/bakhtiyork/devops-tasks"

  database:
    image: postgres 
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

